name: Build
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    strategy:
      matrix:
        multi: [ "true", "false" ]
        mmx: [ "true", "false" ]
        drmkms: [ "true", "false" ]
        fbdev: [ "true", "false" ]
        stereo: [ "true", "false" ]
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: sudo apt-get install meson pkg-config git
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check out flux
        uses: actions/checkout@v3
        with:
          repository: deniskropp/flux
          path: _flux
      - name: Build flux
        working-directory: _flux
        run: |
          ./autogen.sh
          ./configure
          make
          make install
      - name: Setup
        run: meson setup builddir
      - name: Configure
        run: |
          meson configure
          meson configure -Dmmx=${{ matrix.mmx }}
          meson configure -Dmulti=${{ matrix.multi }}
          meson configure -Dfbdev=${{ matrix.fbdev }}
          meson configure -Ddrmkms=${{ matrix.drmkms }}
          meson configure -Dstereo=${{ matrix.stereo }}
        working-directory: builddir
      - name: Compile
        run: meson compile
        working-directory: builddir
